language: c
matrix:
  include:
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      install: ulimit -c

script:
  - cmake -version
  - mkdir build
  - cd build
  - cmake -DTINYUNIT_BUILD_TESTS=ON ..
  - cmake --build .
  - ctest -VV
